-- Find the top 3 customers with the highest total amount spent
SELECT c.name, SUM(p.amount) AS total_amount
FROM Customers c
         JOIN Payments p ON c.customer_id = p.customer_id
GROUP BY c.customer_id
ORDER BY total_amount DESC
    LIMIT 3;

-- Find customers who have made card payments and spent more than 30 currency units
SELECT c.name, SUM(p.amount) AS total_amount
FROM Customers c
         JOIN Payments p ON c.customer_id = p.customer_id
WHERE p.method = 'Credit Card'
GROUP BY c.customer_id
HAVING total_amount > 30;

-- Find the total revenue generated by each service offered by the salon
SELECT s.name AS service_name, SUM(p.amount) AS total_revenue
FROM Services s
         JOIN Appointments a ON s.service_id = a.service_id
         JOIN Payments p ON a.appointment_id = p.customer_id
GROUP BY s.service_id
ORDER BY total_revenue DESC;